# Site settings
title: Jeremy Privett
email: jeremy@jeremyprivett.com
description: >
  Educator. Community Organizer. Consultant. I teach Mid- to Senior-level Developers
  how to be more effective. I teach development teams how to be more
  efficient and focus on the right things. How can I help you?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jeremyprivett.com" # the base hostname & protocol for your site
twitter_username: Atrophius
github_username:  Atrophius

# Build settings
markdown: kramdown
permalink: /:title.html
